services:
  stakit-init:
    user: "101:101"
    environment:
    - REACT_APP_KEYCLOAK_URL=https://keycloak.t0.hosting.kitkube.dk/auth
    - REACT_APP_KEYCLOAK_REALM=stakit
    - REACT_APP_KEYCLOAK_CLIENTID=stakit-ui
    - REACT_APP_INACTIVITY_MAX_MINUTES=30
    - REACT_APP_API_BASEURL=https://stakit.t0.hosting.kitkube.dk/api/v1/
    build:
      context: ../
      dockerfile: ./init.Dockerfile
    volumes:
      - init-dockerentrypoint:/temp/docker-entrypoint.d
      - nginx:/temp/etc/nginx
      - run:/temp/var/run
      - cache-nginx:/temp/var/cache/nginx
  nginx-after-init:
    image: nginxinc/nginx-unprivileged@sha256:8f14986c54fab310b3c69186d814d6238a771f5569cf073c261e675daba88194
    restart: always
    volumes:
      - init-dockerentrypoint:/docker-entrypoint.d
      - nginx:/etc/nginx
      - run:/var/run
      - cache-nginx:/var/cache/nginx
    ports:
      - "3000:80"
    depends_on:
      - stakit-init
  stakit-running:
    environment:
    - REACT_APP_KEYCLOAK_URL=https://keycloak.t0.hosting.kitkube.dk/auth
    - REACT_APP_KEYCLOAK_REALM=stakit
    - REACT_APP_KEYCLOAK_CLIENTID=stakit-ui
    - REACT_APP_INACTIVITY_MAX_MINUTES=30
    - REACT_APP_API_BASEURL=https://stakit.t0.hosting.kitkube.dk/api/v1/
    build:
      context: ../
      dockerfile: ./Dockerfile
    ports:
      - "3030:80"
volumes:
  init-dockerentrypoint:
  nginx:
  cache-nginx:
  run:
  